## Practice Gradient Descent and Linear Regression with PyTorch


In [1]:
import numpy as np
import torch

![linear-regression-training-data](https://i.imgur.com/6Ujttb4.png)



```
yield_apple  = w11 * temp + w12 * rainfall + w13 * humidity + b1
yield_orange = w21 * temp + w22 * rainfall + w23 * humidity + b2
```


In [17]:
# Input (temp, rainfall, humidity)
inputs = np.array([[73, 67, 43], 
                   [91, 88, 64], 
                   [87, 134, 58], 
                   [102, 43, 37], 
                   [69, 96, 70]], dtype='float32')

In [18]:
# Targets (apples, oranges)
targets = np.array([[56, 70], 
                    [81, 101], 
                    [119, 133], 
                    [22, 37], 
                    [103, 119]], dtype='float32')

In [37]:
targets.dtype

torch.float32

In [27]:
type(targets)

torch.Tensor

In [20]:
# Convert inputs and targets to tensor
inputs = torch.from_numpy(inputs)
targets = torch.from_numpy(targets)
print(inputs)
print(targets)

tensor([[ 73.,  67.,  43.],
        [ 91.,  88.,  64.],
        [ 87., 134.,  58.],
        [102.,  43.,  37.],
        [ 69.,  96.,  70.]])
tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])


In [85]:
m1 = np.array([[73, 67, 42],
               [91, 88, 64]])

In [86]:
m1

array([[73, 67, 42],
       [91, 88, 64]])

In [90]:
m2 = np.array([[10, 5, 2],
               [2, 2, 2]])


m2 = m2.transpose()
m2

array([[10,  2],
       [ 5,  2],
       [ 2,  2]])

In [91]:
mult = m1 @ m2

In [92]:
mult

array([[1149,  364],
       [1478,  486]])

In [53]:
m3 = np.array([7, 7, 7])

In [54]:
s = mult + m3

In [55]:
s

array([[737, 342,  91],
       [189, 183, 135]])