# Interesting Numpy Functions with examples

- np.flip
- np.unique
- np.stack
- np.ones_like
- np.flat

The recommended way to run this notebook is to click the "Run" button at the top of this page, and select "Run on Binder". This will run the notebook on mybinder.org, a free online service for running Jupyter notebooks.

In [1]:
# !pip install jovian --upgrade -q

In [2]:
import jovian

<IPython.core.display.Javascript object>

In [3]:
jovian.commit(project='numpy-array-operations', filename='numpy-array-operations.ipynb')

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "aleksmn/numpy-array-operations" on https://jovian.ai/
[jovian] Uploading notebook..
[jovian] Capturing environment..
[jovian] Error: Failed to read Anaconda environment using command: "conda env export -n base --no-builds"
[jovian] Committed successfully! https://jovian.ai/aleksmn/numpy-array-operations


'https://jovian.ai/aleksmn/numpy-array-operations'

Let's begin by importing Numpy and listing out the functions covered in this notebook.

In [4]:
import numpy as np

In [34]:
# List of functions explained 
function1 = np.flip
function2 = np.unique
function3 = np.stack
function4 = np.ones_like
function5 = np.ndarray.flat

## Function 1 - np.flip

Reverse the order of elements along the given axis.

In [6]:
arr1 = np.array([
        [['a', 'b'],
         ['c', 'd']],
        [[11, 22],
         [33, 44]]
        ])

arr1

array([[['a', 'b'],
        ['c', 'd']],

       [['11', '22'],
        ['33', '44']]], dtype='<U21')

In [7]:
# Example 1 - working (change this)
np.flip(arr1, 0)

array([[['11', '22'],
        ['33', '44']],

       [['a', 'b'],
        ['c', 'd']]], dtype='<U21')

EReverse along axis 0.

In [8]:
# Example 2 - working
np.flip(arr1, 2)

array([[['b', 'a'],
        ['d', 'c']],

       [['22', '11'],
        ['44', '33']]], dtype='<U21')

EReverse along axis 2.

In [9]:
# Example 3 - breaking (to illustrate when it breaks)
np.flip(arr1, 4)

AxisError: axis 4 is out of bounds for array of dimension 3

The function breaks because in this array only 3 dimensions.

## Function 2 - np.unique

Returns the sorted unique elements of an array

In [10]:
# Example 1 - working
np.unique([5, 5, 2, 1, 7, 3, 3, 56])

array([ 1,  2,  3,  5,  7, 56])

Returned sorted array of unique integers.

In [11]:
# Example 2 - working
np.unique([5, 7, 2, 1], [5, 4], [5])

(array([1, 2, 5, 7]), array([3, 2, 0, 1]), array([2, 3, 1, 0]))

Returned sorted array of unique arrays.

In [12]:
# Example 3 - breaking (to illustrate when it breaks)
np.unique([5, 7, 2, 1, [5, 4], 5])

TypeError: '<' not supported between instances of 'list' and 'int'

Array can not be sorted, because array consists of lists and integers.

## Function 3 - np.stack

Function to join a sequence of arrays along a new axis.

In [13]:
# Example 1 - working
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

np.stack((a, b))

array([[1, 2, 3],
       [4, 5, 6]])


Arrays stacked along axis 0 by default.

In [14]:
# Example 2 - working

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

np.stack((a, b), axis=1)

array([[1, 4],
       [2, 5],
       [3, 6]])

Arrays stacked along axis 1.

In [15]:
# Example 3 - breaking (to illustrate when it breaks)
a = np.array([1, 2, 3])
b = np.array([4, 5, 6, 7])

np.stack((a, b), axis=1)

ValueError: all input arrays must have the same shape

Error, because all input arrays must have the same shape

With function is useful to make one array from multiple arrays. 

## Function 4 - ones_like

Return an array of ones with the same shape and type as a given array.

In [16]:
# Example 1 - working
my_array = np.arange(10)
my_array = my_array.reshape((5, 2))
my_array

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [17]:
np.ones_like(my_array)

array([[1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1]])

In [18]:
# Example 2 - working
my_array = np.arange(10, dtype=float)
my_array = my_array.reshape((5, 2))

my_array

array([[0., 1.],
       [2., 3.],
       [4., 5.],
       [6., 7.],
       [8., 9.]])

In [19]:
np.ones_like(my_array)

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

Return arraq y with same shape filled with float ones.

In [20]:
# Example 3 - breaking (to illustrate when it breaks)

my_array = np.array((1, 2))
my_second_array = np.array((3, 4))

np.ones_like(my_array, my_second_array)

TypeError: Cannot construct a dtype from an array

Function breaks if given more then one array.

## Function 5 - np.flat

One dimension iterator over array

In [23]:
# Example 1 - working
numbers = np.arange(1, 10).reshape(3, 3)
numbers

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [25]:
numbers.flat[5]

6

Return element 5 from flatten array.

In [28]:
# Example 2 - working
numbers.flat = 5
numbers

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

Made assignment to every element.

In [30]:
# Example 3 - breaking (to illustrate when it breaks)
numbers.flat = 'hello'
number

ValueError: invalid literal for int() with base 10: 'hello'

Can not change integer to string.

## Conclusion

All these functions are very useful when working with arrays.

## Reference Links
Provide links to your references and other interesting articles about Numpy arrays:
* Numpy official tutorial : https://numpy.org/doc/stable/user/quickstart.html
* Numpy reference https://numpy.org/doc/stable/reference/routines.html

In [35]:
jovian.commit(project='numpy-array-operations', filename='numpy-array-operations.ipynb')

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "aleksmn/numpy-array-operations" on https://jovian.ai/
[jovian] Uploading notebook..
[jovian] Capturing environment..
[jovian] Error: Failed to read Anaconda environment using command: "conda env export -n base --no-builds"
[jovian] Committed successfully! https://jovian.ai/aleksmn/numpy-array-operations


'https://jovian.ai/aleksmn/numpy-array-operations'