## Practice PyTorch Basics


In [3]:
import torch

In [6]:
# help(torch)

In [13]:
t1 = torch.tensor([4., 6, 3])
t1

tensor([4., 6., 3.])

In [14]:
t1.dtype

torch.float32

In [19]:
# Vector
t2 =torch.tensor([1., 2, 3, 4])
t2

tensor([1., 2., 3., 4.])

In [20]:
# Matrix
t3 = torch.tensor([[5., 6], 
                   [7, 8], 
                   [9, 10]])
t3

tensor([[ 5.,  6.],
        [ 7.,  8.],
        [ 9., 10.]])

In [21]:
# 3-dimensional array
t4 = torch.tensor([
    [[11, 12, 13], 
     [13, 14, 15]], 
    [[15, 16, 17], 
     [17, 18, 19.]]])
t4

tensor([[[11., 12., 13.],
         [13., 14., 15.]],

        [[15., 16., 17.],
         [17., 18., 19.]]])

In [22]:
print(t1)
t1.shape

tensor(4.)


torch.Size([])

In [23]:
print(t2)
t2.shape

tensor([1., 2., 3., 4.])


torch.Size([4])

In [24]:
print(t3)
t3.shape

tensor([[ 5.,  6.],
        [ 7.,  8.],
        [ 9., 10.]])


torch.Size([3, 2])

In [25]:
print(t4)
t4.shape

tensor([[[11., 12., 13.],
         [13., 14., 15.]],

        [[15., 16., 17.],
         [17., 18., 19.]]])


torch.Size([2, 2, 3])

## Tensor operations and gradients


In [35]:
x = torch.tensor(3., requires_grad=True)
w = torch.tensor(4., requires_grad=True)
b = torch.tensor(5., requires_grad=True)
x, w, b

(tensor(3., requires_grad=True),
 tensor(4., requires_grad=True),
 tensor(5., requires_grad=True))

In [36]:
y = w * x + b
y

tensor(17., grad_fn=<AddBackward0>)

In [37]:
y.backward()

In [38]:
# Display gradients
print('dy/dx:', x.grad)
# y` = (w * x + b)` = (4x + 5)` = 4 + 0 = 4 

print('dy/dw:', w.grad)
# y` = (w * x + b)` = (w * 3 + 5)` = 3 + 0 = 3

print('dy/db:', b.grad)
# y` = (w * x + b)` = (4 * 3 + b)` = 0 + 1 = 1


dy/dx: tensor(4.)
dy/dw: tensor(3.)
dy/db: tensor(1.)
