# Interesting PyTorch Functions

The torch package contains data structures for multi-dimensional tensors and defines mathematical operations over these tensors. Additionally, it provides many utilities for efficient serializing of Tensors and arbitrary types, and other useful utilities.

- torch.arange
- torch.chunk
- torch.narrow
- torch.take
- torch.where

Before we begin, let's install and import PyTorch

In [1]:
# Uncomment and run the appropriate command for your operating system, if required

# Linux / Binder
# !pip install numpy torch==1.7.0+cpu torchvision==0.8.1+cpu torchaudio==0.7.0 -f https://download.pytorch.org/whl/torch_stable.html

# Windows
# !pip install numpy torch==1.7.0+cpu torchvision==0.8.1+cpu torchaudio==0.7.0 -f https://download.pytorch.org/whl/torch_stable.html

# MacOS
# !pip install numpy torch torchvision torchaudio

In [2]:
# Import torch and other required modules
import torch

## Function 1 - torch.arange

Returns a 1-D tensor of size `(end - start) / step` with values from the interval `[start, end)` taken with common difference `step` beginning from start.

Note that non-integer step is subject to floating point rounding errors when comparing against end; to avoid inconsistency, we advise adding a small epsilon to end in such cases.

In [6]:
# Example 1 (working)
torch.arange(8)

tensor([0, 1, 2, 3, 4, 5, 6, 7])

Tensor from 0 to 8.

In [10]:
# Example 2 (working)
torch.arange(5, 6, 0.2)

tensor([5.0000, 5.2000, 5.4000, 5.6000, 5.8000])

Tensor from 5 to 6 with step 0.2.

In [12]:
# Example 3 - breaking (to illustrate when it breaks)
torch.arange([2, 3], 2)

TypeError: arange() received an invalid combination of arguments - got (list, int), but expected one of:
 * (Number end, *, Tensor out, torch.dtype dtype, torch.layout layout, torch.device device, bool pin_memory, bool requires_grad)
 * (Number start, Number end, Number step, *, Tensor out, torch.dtype dtype, torch.layout layout, torch.device device, bool pin_memory, bool requires_grad)


First argument can not be a list. 

## Function 2 - torch.chunk

Splits a tensor into a specific number of chunks. Each chunk is a view of the input tensor.

In [14]:
# Example 1 - working
mytorch = torch.arange(5, 10, 0.2)
mytorch.chunk(2)

(tensor([5.0000, 5.2000, 5.4000, 5.6000, 5.8000, 6.0000, 6.2000, 6.4000, 6.6000,
         6.8000, 7.0000, 7.2000, 7.4000]),
 tensor([7.6000, 7.8000, 8.0000, 8.2000, 8.4000, 8.6000, 8.8000, 9.0000, 9.2000,
         9.4000, 9.6000, 9.8000]))

Split tensor by 2.

In [31]:
# Example 2 - working
mytorch_2 = torch.tensor([[1, 3],[4, 5]])
mytorch_2.chunk(2, 1)

(tensor([[1],
         [4]]),
 tensor([[3],
         [5]]))

Split tensot on second dimension.

In [33]:
# Example 3 - breaking (to illustrate when it breaks)
mytorch_3 = torch.tensor([[1, 3],[4, 5]])
mytorch_3.chunk(2, 2)

IndexError: Dimension out of range (expected to be in range of [-2, 1], but got 2)

Given dimension is out of range

## Function 3 - torch.narrow

`torch.narrow(input, dim, start, length) → Tensor`

Returns a new tensor that is a narrowed version of input tensor. The dimension `dim` is input from `start` to `start + length`. The returned tensor and `input` tensor share the same underlying storage.

In [43]:
# Example 1 - working
x = torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
torch.narrow(x, 1, 0, 1)

tensor([[1],
        [4],
        [7]])

Output is first item from every element.

In [47]:
# Example 2 - working
torch.narrow(x, 0, -1, 1)

tensor([[7, 8, 9]])

Output is last element.

In [50]:
# Example 3 - breaking (to illustrate when it breaks)
torch.narrow(x, 3, 0, 1)

IndexError: Dimension out of range (expected to be in range of [-2, 1], but got 3)

Given dimension (3) is out of range.

## Function 4 - torch.take

Returns a new tensor with the elements of input at the given indices. The input tensor is treated as if it were viewed as a 1-D tensor. The result takes the same shape as the indices.

In [53]:
# Example 1 - working

x = torch.tensor([[1, 2, 3],
                  [4, 5, 6]])
torch.take(x, torch.tensor([1, 4, 5]))

tensor([2, 5, 6])

Output is 1 ,4, 5 elements from source tensor.

In [56]:
# Example 2 - working
torch.take(x, torch.tensor([1, 1, 1]))

tensor([2, 2, 2])

Element with index 1 repeated 3 times.

In [57]:
# Example 3 - breaking (to illustrate when it breaks)
torch.take(x, torch.tensor([1, 4, 8]))

RuntimeError: invalid argument 2: out of range: 8 out of 6 at /pytorch/aten/src/TH/generic/THTensorEvenMoreMath.cpp:212

Element ois out of range.

## Function 5 - torch.where

Return a tensor of elements selected from either x or y, depending on condition.

In [75]:
# Example 1 - working

x = torch.randn(3, 2)
y = torch.ones(3, 2)
print(x)
# print(y)
torch.where(x > 0.5, x, y)

tensor([[-1.1413, -2.3044],
        [-0.4091, -1.0444],
        [ 0.7305,  1.1479]])


tensor([[1.0000, 1.0000],
        [1.0000, 1.0000],
        [0.7305, 1.1479]])

If x > 0.5 return x, else return y.

In [95]:
# Example 2 - working
x = torch.tensor([-1.5, 0, 12, 8, -5], dtype=torch.float64)
torch.where(x > 0, x, .0)

tensor([ 0.,  0., 12.,  8.,  0.], dtype=torch.float64)

Return element > 0, else return 0.

In [96]:
# Example 3 - breaking (to illustrate when it breaks)
torch.where(x > 0, x, 0)

RuntimeError: expected scalar type double but found long int

Dtype in condition do not match.

## Conclusion
PyTorch has a lot of powerfull functions for data manipulation. The official documentation of PyTorch is very usefull and simple to understand.


## Reference Links
Provide links to your references and other interesting articles about tensors
* Official documentation for tensor operations: https://pytorch.org/docs/stable/torch.html
* PyTorch Get Started: https://pytorch.org/get-started/locally/

In [98]:
import jovian
jovian.commit(filename='01-tensor-operations.ipynb')

<IPython.core.display.Javascript object>

[jovian] Update Available: 0.2.38 --> 0.2.41
[jovian] Run `!pip install jovian --upgrade` to upgrade


<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Uploading notebook..
[jovian] Capturing environment..
[jovian] Error: Failed to read Anaconda environment using command: "conda env export -n base --no-builds"
[jovian] Committed successfully! https://jovian.ai/aleksmn/01-tensor-operations


'https://jovian.ai/aleksmn/01-tensor-operations'